spring:
  application:
    name: backend
  data:
    redis:
      host: 60.204.203.236 # TODO
      port: 6379
      password: 1263976832 # TODO
      database: 2
      lettuce:
        pool:
          enabled: true
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: -1ms
  datasource:
    url: jdbc:mysql://60.204.203.236:3306/travel?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true # TODO
    username: root  # TODO
    password: 1263976832  # TODO
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

server:
  port: 20000

jwt:
  secret: 5468576D5A7134743777217A25432A462D4A614E645267556A586E3272357538
  expiration: 86400000

logging:
  level:
    com.asta.backend: debug